### ISSUE TITLE
hw95 feedback

### ISSUE THREAD

**Issue by MichelleYang02** [MKendall17/The-Shendall-Project#2]
**Statement of the problem**
The statement of the problem looks good and concise 

**Recursive Abstraction** 
I don't know if the term "node" should be used because it implies linked lists when this problem deals with two-dimensional arrays. In your additional notes, you guys stated that the "nodes" are referred to as "stepping stones," so maybe it'll be better to replace "nodes" with "stepping stones" to avoid confusion.  

**Base case** 
The base case itself is good, but maybe replace the term "node" (see above) 

**English / Pseudocode** 
The "drop a path on current node" part is a bit ambiguous. I'm not sure what the intention behind this part of the code was. In addition, the recursive backtracking aspect of the problem seems to be missing from the code. You guys have a good general idea of a solution, but there could have been more elaboration on the algorithm. As a side note, I don't think that the "nodes" would be null because they each either have a value of 0, 1 , or 2.

**Comment by benjamin-shen** [comment]
Thanks. This feedback was helpful.  

We agree that the term "node" is pretty outdated now. I replaced it with "position".  
I didn't replace it with "stepping stones" because they could also be walls or treasures. That additional note was incorrect, so I deleted it.  

We meant for "drop a path" to be equivalent to "remove the wall", because there is a "dropA" method defined in the Maze class. This is our interpretation of the latter part of "place a queen, remove the queen" / "place a wall, remove the wall". I didn't change this part; please reopen this issue or write another issue if you disagree.  

Regarding the recursive backtracking aspect: we thought that it was supposed to be inherent in the recursive solution; every time the recursive solution/abstraction finishes (i.e. return true or false), the algorithm would go up one level (i.e. the explorer would backtrack to the adjacent position it came from). Are we missing something? Please reopen this issue or write another issue if you have a different design in mind.  

We agree that nodes can't be null. I nixed that additional note, and replaced it with our description of a "position".
